apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kedacore.github.io/charts
    chart: keda
    targetRevision: 2.20.2
    helm:
      releaseName: keda
      valuesObject:
        nodeSelector:
          workload: platform
        prometheus:
          metricServer:
            enabled: true
            serviceMonitor:
              enabled: true
          operator:
            enabled: true
            serviceMonitor:
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
