apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slurm-operator-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/slinkyproject/charts
    chart: slurm-operator-crds
    targetRevision: 1.2.2
    helm:
      releaseName: slurm-operator-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: slurm-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
